archive = "cosmic"
version = "18.10"
origin = "system76-ubuntu-main"
label = "System76 Ubuntu Main Mirror"
email = "info@system76.com"

[[repos]]
repo = "http://archive.ubuntu.com/ubuntu/pool/main/"
version = { is = "ubuntu18.10" }
arch = { is = "all|amd64" }
